wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693302693.641189
    t:
      1:
      - 1
      - 11
      - 41
      - 43
      - 49
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 43
      - 49
      - 55
      - 63
      3:
      - 23
      - 35
      4: 3.11.4
      5: 0.15.9
      6: 4.32.0
      8:
      - 5
